language: python
dist: xenial
python: 3.6

notifications:
  email: false

services:
  - docker

sudo: required

env:
  global:
    - DOCKER_IMAGE=pywr/manylinux1_x86_64-glpk
  matrix:
    - PYBIN=/opt/python/cp36-cp36m/bin BUILD_DOC=1
    - PYBIN=/opt/python/cp36-cp36m/bin PYWR_BUILD_TRACE=true
    - PYBIN=/opt/python/cp37-cp37m/bin

install:
  - docker pull $DOCKER_IMAGE
  - |
    if [ "$PYWR_BUILD_TRACE" -eq "true" ]; then
      pip install python-coveralls
    fi

script:
  - |
    docker run --rm -v `pwd`:/io \
      -e PYBIN=$PYBIN \
      -e PYWR_BUILD_TRACE=$PYWR_BUILD_TRACE \
      -e BUILD_DOC=$BUILD_DOC \
      $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - |
    if [ "$BUILD_DOC" -eq "1" ]; then
      if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
        if [[ -z "$TRAVIS_TAG" ]]; then
          DEPLOY_DIR=master;
        else
          DEPLOY_DIR="v-$TRAVIS_TAG";
        fi

        pip install doctr
        doctr deploy --deploy-repo pywr/pywr-docs \
          --build-tags --built-docs pywr-docs/html $DEPLOY_DIR
      fi
      fi
    fi

after_success:
  - coverage combine
  - coveralls
