language: generic

sudo: false

cache:
    directories:
        - ${HOME}/miniconda3

env:
    matrix:
        - CONDA_NPY=111  CONDA_PY=27
        - CONDA_NPY=111  CONDA_PY=34
        - CONDA_NPY=113  CONDA_PY=36

install:
    - |
      if [ ! -f ${HOME}/miniconda3/bin/conda ] ; then
          echo "Fresh miniconda install..."
          MINICONDA_URL="https://repo.continuum.io/miniconda"
          MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
          wget ${MINICONDA_URL}/${MINICONDA_FILE}
          rm -rf ${HOME}/miniconda3
          bash ${MINICONDA_FILE} -b -p ${HOME}/miniconda3
      fi
      export PATH=${HOME}/miniconda3/bin:$PATH

      conda config --add channels snorfalorpagus
      conda config --add channels conda-forge
      
      conda update --yes conda

      conda config --set show_channel_urls true
      conda install --yes --quiet conda-build

script:
    - conda build conda-recipe

before_cache:
    - rm -rf ${HOME}/miniconda3/conda-bld/*
    - rm -rf ${HOME}/miniconda3/envs/*

notifications:
    email: false
