notifications:
  email: false

services:
  - docker

sudo: required

env:
  global:
    - DOCKER_IMAGE=pywr/manylinux1_x86_64-glpk
  matrix:
    - PYBIN=/opt/python/cp36-cp36m/bin
    - PYBIN=/opt/python/cp37-cp37m/bin

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io -e PYBIN=$PYBIN $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
